# Generated by Django 4.2.2 on 2023-06-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_subject", models.CharField(max_length=100)),
                ("content_article", models.TextField(max_length=3000)),
                (
                    "user_id",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.iddefaultinfo",
                    ),
                ),
            ],
        ),
    ]
